# ead:
#   serviceRegistry:
#     username: serviceregistry
#     password: '96082553'
#   configServer:
#     username: configserver
#     password: '81600833'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost